language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - hhvm
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - sudo chmod 777 -R /home/travis/build/D3Catalyst/laravel-4-resource-compress/public/

script: phpunit